server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST


globalcors:
  add-to-simple-url-handler-mapping: true
  corsConfigurations:
    '[/**]':
      allowedOrigins: "*"
      allowedHeaders: "*"
      allowedMethods: "*"
      allowCredentials: true
